### ISSUE TITLE
Remove support for Shockwave applet in student code

### ISSUE THREAD

**Issue by gioele** [cceh/palonline#1]
The Javascript code is mature enough and there is no need any more to support the Shockwave applet in the code for students.

The code that inject the Shockwave applet should be removed and the "Javascript" setting nullified in the DB for all users (existing and newly created).

**Comment by olvidalo** [comment]
Originally, when a user would log in the value of the row *Javascript* from the 'benutzer' table of the database would be read, containing either 1 or 0. Then, *_SESSION['js']* would be set according to this value. *code-fragments/bildschirm.php* would then execute either the javascript or the shockwave applet code depending on this variable.

Now, the *Javascript* row is ignored and the 'js' session variable has been removed, as well as any code path that depended on the shockwave applet. Also, the Javascript row has been removed from the user information overview in *benutzer.php'

* e03a646 remove partials/shockwave.inc
* 1f20e37 removed 'js' session variable from login.php
* 1e78cda removed 'js' session variable from benutzer.php
* 884727d assume javascript enabled in code-fragments/bildschirm.php (#1)
