### ISSUE TITLE
Glossar links in `/sitzung.php?bildschirmID=218&stundenplanID=75` behave strange

### ISSUE THREAD

**Issue by GVogeler** [cceh/palonline#10]
the [[...]] references are all solved to the GET-parameter ?stundenplanID which is correct for the first ('Achilius-Brief aus dem 4. Jahrhundert' refers to stundenplanID=75) but wrong for the rest.

**Comment by GVogeler** [comment]
Same in http://www.palaeographie-online.de/glossar.php?Stichwort=%27Register%27
=> the resolving mechanism for the [[...]]-references should distinguish between the type of reference indicated by $: in \$(.*?)\] $1 signifies the type of reference different from the default reference to glossar.php

**Comment by olvidalo** [comment]
in verweise.inc:17, `VerweisAufGlossar`, `$Ansicht` would be set to the default value "glossar" only at the beginning of the function. in the loop that parses for links, as soon as it encountered a link with a specific *ansicht* set, e.g. "stundenplan" by using the `$` sign, `$Ansicht` would be set to that and not be reset to "glossar" for the remaining iterations until there would be another link setting a specific ansicht.

now, everytime no '$' specifier is found in the link, `$Ansicht` is always set to "glossar".
