### ISSUE TITLE
Modifying `/vhb_intern/form.php?tab=stundenplan` returns a blank `write.php`

### ISSUE THREAD

**Issue by GVogeler** [cceh/palonline#11]
e.g. `/vhb_intern/form.php?tab=stundenplan&ID=561`

Modifications of other object types/tables (bildschrim, benutzer) work.

**Comment by olvidalo** [comment]
wrong query object was used in write.php:123

**Comment by gioele** [comment]
Fixed in 1a2d4524e796c689fd5c99c6d7584da6ff88363d.
