### ISSUE TITLE
write.php of a new user has not Kontext

### ISSUE THREAD

**Issue by GVogeler** [cceh/palonline#13]
The Kontext section of the write.php-response should include the kontext.inc functionality as in the form.php.

![clipboard01](https://cloud.githubusercontent.com/assets/324006/7062338/7b6f7f7a-de9c-11e4-96dd-275c3e28e5f8.jpg)

**Comment by gioele** [comment]
Is this the expected result?

![write.php screenshot](https://cloud.githubusercontent.com/assets/237141/7064684/15abd8f4-deb1-11e4-9c87-e9fb9a20b79a.png)

**Comment by GVogeler** [comment]
yes!

**Comment by gioele** [comment]
Fixed in 741e12c6ed2fd2d7e850263df9070e622fff69e8.
