### ISSUE TITLE
user inscription returns empty write.php

### ISSUE THREAD

**Issue by GVogeler** [cceh/palonline#17]
and doesn't store data

**Comment by gioele** [comment]
Which kind of user inscription?

**Comment by gioele** [comment]
@olvidalo: I think the problem arises because the scaffolding code tries to set up the Javascript field for new users. From the logs:

    [Tue Apr 14 07:40:08 2015] [error] [client 80.135.35.187] PHP Fatal error: 
    Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity
    constraint violation: 1048 Column 'Javascript' cannot be null' in .../write.php:135

I think we need a second round of Javascript purging: altering the DB to drop the column and removing the last references to that field from the code. After this the scaffolding code will generate SQL INSERT queries without any reference to the `Javascript` field and the error will be gone.

**Comment by GVogeler** [comment]
manual inscription

Am 14.04.2015 um 11:15 schrieb Gioele:

**Comment by olvidalo** [comment]
I have changed the database so that `Javascript` can now be NULL, so it can be left blank at manual inscription. Tomorrow I'll remove the Javascript column and update the code.

**Comment by olvidalo** [comment]
I've removed last references to `Javascript` from the code and deleted the row from the table.

646874091dc07468fee31fbc9a1bf1f24a2aba96

**Comment by GVogeler** [comment]
Manual inscription still returns
PHP PDO Error 23000]
Message:	SQLSTATE[23000]: Integrity constraint violation: 1048 Column 
'inscription' cannot be null
Code:	23000
File: 
/afs/.rrz.uni-koeln.de/vol/www/projekt/palonline/http/docs/vhb_intern/write.php
Line:	137
Trace:	

0#	file:	 
/afs/.rrz.uni-koeln.de/vol/www/projekt/palonline/http/docs/vhb_intern/write.php
0#	line:		137
0#	function:		execute
0#	class:		PDOStatement
0#	type:		->

Unfortunately I don't remember what the purpose of 
`benutzer`.`incription` and `benutzer`.`inscribe_date` are. Maybe they 
can be removed savely too.

As far as I remember:

inscribe.php: makes use of the fields
Nachname, Vorname, Kennung, Kennwort, EMail, Rolle (assigned "Student" 
via a hidden input field)

manual inscription uses Nachname, Vorname, Kennung, Kennwort, Rolle, 
EMail, Matrikelnummer, Heimatuni, Strasse, PLZ, Ort, Geschlecht, 
Studienfach, Abschluss

Eintragsdatum and benutzer_id are set automatically.

**Comment by gioele** [comment]
The Javascript code has been fixed and the associated code change is 646874091dc07468fee31fbc9a1bf1f24a2aba96.

I have moved the last comment to its own issue.
