### ISSUE TITLE
«Integrity constraint violation: 1048 Column 'AnmeldungsIP' cannot be null» while adding a new user

### ISSUE THREAD

**Issue by gioele** [cceh/palonline#18]
New users cannot be added because a `SQLSTATE[23000]` error is generated by `write.php:137`.

The column referred by the error `AnmeldungsIP` is a leftover from previous code, it can be safely removed.

**Comment by olvidalo** [comment]
I have removed `AnmeldungsIP` from the database so it does not appear in the new user form anymore.
