### ISSUE TITLE
"New user" email to lecturer is not sent

### ISSUE THREAD

**Issue by gioele** [cceh/palonline#5]
When a user subscribes to PalOnline the system should send an email to the lecturer with some details about the newly created user. This email is not sent at the moment.

The code responsible for this is in 

    vhb_intern/write.php

near the comment

    //Verschickt eine Begrüßungsmail, wenn es eine Neuanmeldung ist.

**The code should be changed to use the `email_to_admin` function described in #6.**

**Comment by olvidalo** [comment]
if i read the code correctly, write.php is only used when a user is created manually using the (not too self-explanatory) form
    http://www.palaeographie-online.de/vhb_intern/form.php?Neu=Y&tab=benutzer

should the welcome mail and the admin mail also be sent when a user inscribes herself? then i would put some code that does this in inscribe.php

**Comment by GVogeler** [comment]
The new-user mail is only necessary when inscription is made by hand.

A welcome mail on self-inscription is a nice-to-have but no priority at all.

A welcome mail on self-inscription should only be sent to the user not 
to the teachers.


Am 01.04.2015 um 12:25 schrieb Marcel:

**Comment by gioele** [comment]
Fixed though various commits, the last of which is 37db83e912fc54a121a8ac2a0abef5603b5691d8.
