### ISSUE TITLE
Implement `email_to_admin`

### ISSUE THREAD

**Issue by gioele** [cceh/palonline#6]
The new-style `email_to_admin` function should mirror the existing `email_to_user` function, using the globa `['bcc']` field as the destination address.

**Comment by olvidalo** [comment]
i have added a preliminary but working email_to_admin function to mail.php in ccd57193c67a98c979d6387620b828a309dc441d.

**Comment by gioele** [comment]
Finished in 496e8091ee6068633c497a9890d75a00dfe97640.
