### ISSUE TITLE
Missing file `version.php`

### ISSUE THREAD

**Issue by gioele** [cceh/palonline#7]
The file `version.php` has not been copied over from the previous installation. The rationale was that the code could be easily refactored to avoid fetching that file. It turns out that it is not possible to do easily with the current code, so the best solution is to copy use again a `version.php` file.

**Comment by GVogeler** [comment]
I've copied it on dialog.

**Comment by gioele** [comment]
It also needed a bit of tender love to be adapted to the new code structure. :)

Fixed in 7362d8487bc4b3a32caa261bb19ea0ad4d3759a6.
